###############################################################################
# Airbyte K8s secrets (OSS)
# Usage: kubectl apply -f secrets.yaml -n airbyte
###############################################################################
apiVersion: v1
kind: Secret
metadata:
  name: airbyte-postgres-secret
  namespace: airbyte
type: Opaque
stringData:
  password: "${PG_ADMIN_PASSWORD}"

---
apiVersion: v1
kind: Secret
metadata:
  name: airbyte-minio-secret
  namespace: airbyte
type: Opaque
stringData:
  access-key: "${MINIO_ACCESS_KEY:-minioadmin}"
  secret-key: "${MINIO_SECRET_KEY:-minioadmin}"
